language: node_js
install:
  - yarn
node_js:
  - "10"
script:
  - npm run build:demo

after_script:
  - git add .
  - git commit -m "deploy:online demo"
  - git push "https://${GITHUB_TOKEN}@${GITHUB_REPO}" master:${PUSH_BRANCH}

branches:
  only:
    - master

cache:
  directories:
    - "node_modules"

deploy:
 provider: pages
 skip-cleanup: true
 github-token: $GITHUB_TOKEN
 keep-history: true
 on:
  branch: master
